services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom/Random
    volumes:
      - ./custom-nodes:/home/node/.n8n/custom/Random
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local
